### ISSUE TITLE
Porting to nintendo 3ds or nintendo switch 

### ISSUE THREAD

**Issue by BanhMi939** [Lisowolf/HangarEmulator#33]
Please port this awsome emulator to nintendo switch please please please

**Comment by Lisowolf** [comment]
Hello, thanks for appreciating :)
Unfortunately, this application is not a full-fledged emulator. This application, like J2ME-apps, relies entirely on the JVM, it only launches the MIDlet and contains the missing libraries that are used by J2ME applications. That is, it does too little small part of the work to be ported to another platform, so at the moment this task seems impossible for me.

But I heard that it is possible to install Android on the Nintendo Switch, and I guess that is possible to run on the Android the J2ME Loader: https://github.com/nikita36078/J2ME-Loader

**Comment by BanhMi939** [comment]
Well, thanks for the answer, but i dont want to boot into android mode evertime i want i play java game so... Thanks you anw.
